### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by kun-dragon** [HengLan/VastTrack#3]
Great work! In your experiments in the paper, I'm confused about the parameters used for evaluating the trackers. Are these parameters obtained from the original papers or trained using a subset of your dataset?

**Comment by HengLan** [comment]
Hi

Thanks for your interest. In the experiments, all the 25 evaluated trackers are assessed as they are, which means the parameters are adopted from the original papers/implementations without modifications (see this in the introduction of evaluated trackers in the paper).

Hope it helps.
