### ISSUE TITLE
The attribute analysis plot

### ISSUE THREAD

**Issue by Jasper0420** [HengLan/VastTrack#7]
![image](https://github.com/HengLan/VastTrack/assets/63343279/f73237f5-ce5e-42d3-9e48-54e8e10c5d01)
Thank you for your contribution to tracking community engagement!
I'm going to FOLLOW your work and measure it on the VastTrack dataset, and I was wondering how you drew your attribute analysis plot based on the VastTrack dataset? Can you provide the raw_tracking for those methods in the graph. I did not find them! Thanks!
Good luck!

**Comment by HengLan** [comment]
Hi 

Thanks for your interest in our work.

You can refer to the code here (https://github.com/HengLan/VastTrack/tree/main/MatlabEvaluationToolkit) to reproduce the results and plots. For the attribute analysis, just look at line 140 in run_tracker_performance_evaluation.m file. All tracking results are provided if you look at that page. 

Please let us know if you have further questions.

Hope it helps. Thanks.

**Comment by Jasper0420** [comment]
Thank you for your excellent work!
I did not notice it due to my carelessness!
Thanks again!

**Comment by Jasper0420** [comment]
I found a small error
In the Robot Dog class in the test set, its groundtruth.txt is incorrectly named, it should be Groundtruth.txt, which can lead to errors when reading the data. This might be better if the user is alerted in the Readme.
