### ISSUE TITLE
Inconsistent GT labeling for Rocket category

### ISSUE THREAD

**Issue by Jasper0420** [HengLan/VastTrack#8]
![image](https://github.com/HengLan/VastTrack/assets/63343279/c1f5fd91-1d4d-4620-9482-9c4aab5b6306)
The GT in Rocket-1 doesn't match the GT in toolkit and its initial template frame is [0,0,0,0], which can cause serious errors, maybe you  should check it.

**Comment by HengLan** [comment]
Thanks for pointing it out. We will check out and fix it.
